# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20161126_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='track',
            field=models.IntegerField(default=1),
        ),
    ]
